[versions]
agp = "8.5.1"
bigMath = "2.3.2"
coreSplashscreen = "1.0.1"
coreSplashscreenVersion = "1.0.0"
interpolatorVersion = "1.0.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.0"
constraintlayout = "2.1.4"
animationCoreAndroid = "1.6.7"
playServicesAds = "23.1.0"
review = "2.0.1"
runtimeAndroid = "1.6.7"
navigationRuntime = "2.7.7"
appUpdate = "2.1.0"

[libraries]
androidx-interpolator = { module = "androidx.interpolator:interpolator", version.ref = "interpolatorVersion" }
app-update-ktx = { module = "com.google.android.play:app-update-ktx", version.ref = "appUpdate" }
big-math = { module = "ch.obermuhlner:big-math", version.ref = "bigMath" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
core-splashscreen-v100 = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreenVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
animation-core-android = { group = "androidx.compose.animation", name = "animation-core-android", version.ref = "animationCoreAndroid" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
review = { module = "com.google.android.play:review", version.ref = "review" }
review-ktx = { module = "com.google.android.play:review-ktx", version.ref = "review" }
runtime-android = { group = "androidx.compose.runtime", name = "runtime-android", version.ref = "runtimeAndroid" }
navigation-runtime = { group = "androidx.navigation", name = "navigation-runtime", version.ref = "navigationRuntime" }
app-update = { group = "com.google.android.play", name = "app-update", version.ref = "appUpdate" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

